services:
  mysql:
    image: mysql:latest
    container_name: mysql_achiva
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DB}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
#    volumes:
#      - mysql_data:/var/lib/mysql

#volumes:
#  mysql_data: