aws:
  region: ${AWS_REGION:ap-northeast-2}

  s3:
    access-key-id: ${AWS_S3_ACCESS_KEY_ID}
    secret-access-key: ${AWS_S3_SECRET_ACCESS_KEY}
    bucket-name: ${AWS_S3_BUCKET_NAME}

  cognito:
    access-key-id: ${AWS_COGNITO_ACCESS_KEY_ID}
    secret-access-key: ${AWS_COGNITO_SECRET_ACCESS_KEY}
    user-pool-id: ${AWS_COGNITO_USER_POOL_ID}
