spring:
  profiles:
    active: local

  config:
    import:
      - classpath:application-aws.yml

  application:
    name:
      Achiva

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_MmVclnRmP
      client:
        registration:
          cognito:
            client-id: 6mp9rrcnrl8h8hd7tuubj3689u
            client-secret: ${DOC_LOGIN_CLIENT_SECRET}
            scope:
              - email
              - openid
              - phone
            redirect-uri: "{baseUrl}/login/oauth2/code/cognito"
            client-name: Cognito
        provider:
          cognito:
            issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_MmVclnRmP
            user-name-attribute: username

#logging:
#  level:
#    org:
#      springframework:
#        security: DEBUG
#        security.oauth2:
#          client: DEBUG
#          core: DEBUG
#          client.endpoint.DefaultAuthorizationCodeTokenResponseClient: TRACE
#      springframework.web.client: TRACE