spring:
  profiles:
    active: local

  config:
    import:
      - classpath:application-aws.yml

  application:
    name:
      Achiva

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://cognito-idp.ap-northeast-2.amazonaws.com/ap-northeast-2_MmVclnRmP

  app:
    security:
      client-id:
        - a3kaacto97fom3ved1bjivbiu